/**
 * Production-readiness regression tests
 * ============================================================================
 * Guards against three bugs found in a production-readiness review:
 *
 * 1. `tws()`/`useTws()` (imported from `src/core/tws.js`, the file backing the
 *    published `tailwind-to-style` and `tailwind-to-style/tws` entry points)
 *    called `tailwindCache.getOrGenerate()` without the required `generateFn`/
 *    `convertFn` arguments. That threw on first use and was silently
 *    swallowed by a try/catch, so `tws()` returned `""`/`{}` unless something
 *    else (e.g. `tw()`) had already populated the shared cache singleton.
 *    Fix: `src/core/tws.js` now re-exports the single implementation in
 *    `src/index.js` instead of duplicating it.
 *
 * 2. `createSSRCollector()` never actually received CSS generated by
 *    `tw()`/`twsx()` — the real injection paths in `src/index.js` and
 *    `src/className/index.js` only checked their own local/legacy SSR flags,
 *    never the modern collector's state. `ssr.extract()` always returned "".
 *    Fix: both injection paths now delegate to `isSSRCollecting()`/
 *    `collectSSRCSS()` in `src/utils/ssr.js`, the single source of truth.
 *
 * 3. The SSR collector's "active collector" was a single module-level
 *    variable, so concurrent requests on the same Node process could leak
 *    CSS into each other. Fix: `collector.run(fn)` uses Node's
 *    AsyncLocalStorage (when available) to scope the active collector to the
 *    current async call chain.
 * ============================================================================
 */

import { tw, tws, createSSRCollector } from '../src/v4/index.js';
// twsx() isn't part of the v4 unified surface (it's reached via tw()'s slots
// mode or the `tailwind-to-style/twsx` subpath) but shares the same
// underlying engine/cache/SSR state, so importing it straight from the
// monolith is equivalent and lets us test it directly.
import { twsx } from '../src/index.js';

describe('tws() standalone (bug #1)', () => {
  it('returns real CSS on the very first call, without any prior tw()/twsx() call', () => {
    // Regression guard: previously this returned "" because the cache
    // singleton hadn't been "accidentally" populated by another API first.
    const result = tws('bg-blue-500 text-white p-4');
    expect(result).toEqual(expect.any(String));
    expect(result.length).toBeGreaterThan(0);
    expect(result).toMatch(/background-color/);
    expect(result).toMatch(/padding/);
  });

  it('returns a populated object when convertToJson is true', () => {
    const result = tws('flex items-center gap-4', true);
    expect(result).toMatchObject({ display: 'flex' });
  });
});

describe('createSSRCollector() (bug #2)', () => {
  it('captures real CSS generated by tw() when rendering inside run()', () => {
    const ssr = createSSRCollector();

    const className = ssr.run(() => tw('flex items-center gap-2 bg-teal-500'));

    expect(className).toContain('tw-flex');
    const css = ssr.extract();
    expect(css).toContain('.tw-flex');
    expect(css).toContain('.tw-bg-teal-500');
  });

  it('captures CSS generated by twsx() when rendering inside run()', () => {
    const ssr = createSSRCollector();

    ssr.run(() => twsx({ '.ssr-probe': 'bg-amber-500 p-2' }));

    const css = ssr.extract();
    expect(css).toContain('.ssr-probe');
  });
});

describe('createSSRCollector() concurrency isolation (bug #3)', () => {
  it('does not leak CSS between two concurrent run() calls, including CSS generated after an await', async () => {
    async function fakeRequest(firstClass, secondClass) {
      const ssr = createSSRCollector();
      return ssr.run(async () => {
        tw(`flex ${firstClass}`);
        // Yield to the event loop to simulate async rendering (streaming SSR,
        // data fetching, Suspense, etc.) interleaving with other concurrent
        // requests. Generating more CSS *after* this await is what actually
        // requires AsyncLocalStorage-based isolation rather than a plain
        // module-level "active collector" variable.
        await new Promise((resolve) => setTimeout(resolve, Math.random() * 15));
        tw(`p-2 ${secondClass}`);
        return ssr.extract();
      });
    }

    const [cssA, cssB] = await Promise.all([
      fakeRequest('bg-emerald-500', 'text-emerald-900'),
      fakeRequest('bg-fuchsia-500', 'text-fuchsia-900'),
    ]);

    expect(cssA).toContain('emerald');
    expect(cssA).not.toContain('fuchsia');
    expect(cssB).toContain('fuchsia');
    expect(cssB).not.toContain('emerald');
  });
});
