/**
 * DOM CSS Injector
 * 
 * Handles automatic CSS injection into the DOM.
 * Supports SSR mode, HMR-friendly block registry, and hash-based deduplication.
 * 
 * @module injector/dom
 */

import { IS_BROWSER } from "../shared/constants.js";
import { isSSRCollecting, collectSSRCSS } from "../utils/ssr.js";
import { injectedCssHashSet, cssBlockRegistry } from "../shared/cache.js";
import { getCssHash } from "../shared/hash.js";
import { evictSet } from "../shared/cache.js";
import { performanceMonitor } from "../utils/performanceMonitor.js";
import { logger } from "../utils/logger.js";

/**
 * Rebuild the style tag from the CSS block registry.
 * 
 * Used for slot-based updates where each twsx() call owns its own CSS block.
 * Rebuilds the entire style tag to avoid stale CSS from previous HMR cycles.
 * 
 * @private
 */
export function rebuildStyleTag() {
  let styleTag = document.getElementById("twsx-auto-style");
  if (!styleTag) {
    styleTag = document.createElement("style");
    styleTag.id = "twsx-auto-style";
    styleTag.setAttribute("data-twsx", "");
    document.head.appendChild(styleTag);
  }
  styleTag.textContent = [...cssBlockRegistry.values()].join("\n");
}

/**
 * Automatically inject CSS into the DOM or collect for SSR.
 * 
 * Supports three modes:
 * 1. SSR mode: Delegates to utils/ssr.js collector
 * 2. Slot-based mode (with sourceKey): HMR-friendly block registry
 * 3. Hash-based mode (no sourceKey): Legacy deduplication
 * 
 * @param {string} cssString - CSS to inject
 * @param {string|null} sourceKey - Optional unique key for slot-based updates
 * 
 * @example
 * // Slot-based (HMR-friendly)
 * autoInjectCss('.btn { color: blue; }', 'twsx-call-123');
 * 
 * @example
 * // Hash-based (legacy)
 * autoInjectCss('.btn { color: blue; }');
 * 
 * @example
 * // SSR mode (delegates to ssr.js)
 * startSSR();
 * autoInjectCss('.btn { color: blue; }');
 * const css = stopSSR();
 */
export function autoInjectCss(cssString, sourceKey = null) {
  const marker = performanceMonitor.start("css:inject");

  try {
    // SSR mode: collect CSS strings instead of DOM injection. Delegates to
    // the shared collector in ./utils/ssr.js so both the legacy
    // startSSR()/stopSSR() pair and the modern createSSRCollector() actually
    // receive the CSS generated by tw()/twsx().
    if (isSSRCollecting()) {
      collectSSRCSS(cssString);
      performanceMonitor.end(marker);
      return;
    }

    if (IS_BROWSER) {
      if (sourceKey) {
        // Slot-based update: each unique twsx(obj) call owns its own CSS block.
        // When styles change (new content, same logical call site via cacheKey)
        // the old slot is replaced and the style tag is fully rebuilt, so no
        // stale rules from previous HMR cycles can pile up.
        const existing = cssBlockRegistry.get(sourceKey);
        if (existing === cssString) {
          // Identical content – nothing to do.
          performanceMonitor.end(marker);
          return;
        }
        cssBlockRegistry.set(sourceKey, cssString);
        rebuildStyleTag();

        if (cssBlockRegistry.size % 10 === 0) {
          logger.debug(
            `CSS registry stats: ${cssBlockRegistry.size} blocks registered`
          );
        }
        performanceMonitor.end(marker);
        return;
      }

      // Fallback path (e.g. direct autoInjectCss calls without a sourceKey):
      // keep the original hash-based dedup + append behaviour.
      const cssHash = getCssHash(cssString);
      if (injectedCssHashSet.has(cssHash)) {
        performanceMonitor.end(marker);
        return;
      }

      injectedCssHashSet.add(cssHash);
      evictSet(injectedCssHashSet);

      let styleTag = document.getElementById("twsx-auto-style");
      if (!styleTag) {
        styleTag = document.createElement("style");
        styleTag.id = "twsx-auto-style";
        styleTag.setAttribute("data-twsx", "");
        document.head.appendChild(styleTag);
      }

      // Append CSS to style tag using textContent for reliability
      // Note: insertRule + textContent mixing destroys CSSOM rules,
      // so we use textContent exclusively for consistent behavior
      // with @keyframes, @media, and other nested CSS blocks.
      styleTag.textContent += `\n${cssString}`;

      // Log injection stats periodically
      if (injectedCssHashSet.size % 10 === 0) {
        logger.debug(
          `CSS injection stats: ${injectedCssHashSet.size} unique stylesheets injected`
        );
      }
    }
    performanceMonitor.end(marker);
  } catch (error) {
    performanceMonitor.end(marker);
    logger.error("Error injecting CSS:", error);
  }
}
