import { register } from 'tailwind-to-style/register';

register.all({
  ':root': {
    '--c-brand':        '#6366f1',
    '--c-brand-hover':  '#4f46e5',
    '--c-brand-light':  '#eef2ff',
    '--c-brand-ring':   'rgba(99,102,241,.35)',
    '--c-bg':           '#f9fafb',
    '--c-surface':      '#ffffff',
    '--c-border':       '#e5e7eb',
    '--c-border-focus': '#6366f1',
    '--c-text':         '#111827',
    '--c-text-muted':   '#6b7280',
    '--c-text-light':   '#9ca3af',
    '--c-success':      '#16a34a',
    '--c-success-bg':   '#f0fdf4',
    '--c-warning':      '#d97706',
    '--c-warning-bg':   '#fffbeb',
    '--c-danger':       '#dc2626',
    '--c-danger-bg':    '#fef2f2',
    '--c-info':         '#2563eb',
    '--c-info-bg':      '#eff6ff',
    '--shadow-sm':      '0 1px 2px rgba(0,0,0,.05)',
    '--shadow-md':      '0 4px 12px rgba(0,0,0,.08)',
    '--shadow-lg':      '0 8px 32px rgba(0,0,0,.12)',
    '--radius-sm':      '6px',
    '--radius-md':      '8px',
    '--radius-lg':      '12px',
    '--radius-xl':      '16px',
    '--radius-full':    '9999px',
  },
  '*':    { 'box-sizing': 'border-box', margin: '0', padding: '0' },
  'body': {
    tw: 'antialiased',
    'font-family': "Inter, system-ui, -apple-system, 'Segoe UI', sans-serif",
    'font-size': '15px',
    'line-height': '1.6',
    color: 'var(--c-text)',
    'background-color': 'var(--c-bg)',
  },
});
